# Generated by Django 5.2.1 on 2025-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_options_article_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('moderated', 'В модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'Архивированно')], default='moderated', max_length=10, verbose_name='Статус'),
        ),
    ]
