version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - ./libertypost/static:/app/libertypost/static
      - ./libertypost/media:/app/libertypost/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./libertypost/static:/app/libertypost/static
      - ./libertypost/media:/app/libertypost/media
    depends_on:
      - web

volumes:
  postgres_data:
