# Generated by Django 5.2.1 on 2025-05-12 08:35

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=account.models.get_random_avatar, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
