upstream libertypost {
    server web:8000;
}

server {
    listen 80;
    server_name binido.online www.binido.online;
    client_max_body_size 100M;

    location /static/ {
        alias /app/libertypost/staticfiles/;
        autoindex on;
        access_log off;
        expires max;
        add_header Cache-Control "public, immutable";
    }

    location /static/admin/ {
        alias /app/libertypost/staticfiles/admin/;
        access_log off;
        expires max;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /app/libertypost/media/;
        access_log off;
        expires max;
        add_header Cache-Control "public, max-age=2592000";
    }

    location / {
        proxy_pass http://libertypost;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
        
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
